---
- name: Create new VM
  hosts: hypervisor
  become: true

  vars:
    domain: mulli.org
    vm_name: monastery
    vmid_list:
      - "151"
      - "152"
      - "153"
      - "154"
      - "155"

  tasks:
  - name: Copy over script
    ansible.builtin.copy:
      src: ./ubuntu-2204-cloud.cfg
      dest: /tmp/ubuntu-2204-cloud.cfg

  - name: Copy over ssh key
    ansible.builtin.copy:
      src: ./ssh-key.pub
      dest: /tmp/ssh-key.pub

  - name: Run build script
    ansible.builtin.script:
      chdir: /tmp/
      cmd: "./create-vm.sh {{ item }} {{ vm_name }}-{{ item }}"
    loop: "{{ vmid_list }}"

  - name: Get network info
    ansible.builtin.fetch:
      flat: true
      src: /tmp/vm-{{ item }}-interfaces.log
      dest: ./
    loop: "{{ vmid_list }}"

  - name: Cleanup network file
    ansible.builtin.file:
      path: /tmp/vm-{{ item }}-interfaces.log
      state: absent
    loop: "{{ vmid_list }}"

  - name: Create node list
    vars:
      net_info_file: "vm-{{ item }}-interfaces.log"
      vm_hostname: "{{ vm_name }}-{{ item }}.{{ domain }}"
      inventory_file: hosts
    local_action: ansible.builtin.shell bash get-ip-addr.sh {{ net_info_file }} {{ vm_hostname }} >> {{ inventory_file }}
    loop: "{{ vmid_list }}"
           
 

 

