---
- hosts: "control-plane"
  become: true

  tasks:
    - name: Initialize cluster
      shell: |
        kubeadm init --pod-network-cider={{ cluster_pod_net_cidr }}

    - name: Get join token
      shell: kubeadm token create --print-join-command | tee /tmp/cluster-join-command.sh
      register: k8s_cluster_join_command

    - name: Fetch join script
      ansible.builtin.fetch: 
        flat: true
        src: /tmp/cluster-join-command.sh 
        dest: ./

