---
- name: New debian system provisioning
  hosts: localhost

  tasks:
  - name: Update
    become: true
    ansible.builtin.apt:
      update_cache: yes

  - name: Install common use packages
    become: true
    ansible.builtin.apt:
      name:
      - curl
      - vim
      - git
      - net-tools
      - neofetch
      state: present
