---
- name: New debian system provisioning
  hosts: localhost

  vars:
    provision_src: "10.0.0.20:4200"

  tasks:
  - name: Update
    become: true
    ansible.builtin.apt:
      update_cache: yes

  - name: Install common use packages
    become: true
    ansible.builtin.apt:
      name:
      - curl
      - vim
      - gpg
      - net-tools
      - neofetch
      state: present

  - name: Configure personal user
    ansible.builtin.user:
      name: nitor
      append: true
      groups: sudo,adm

  - name: Add personal authorized key
    ansible.builtin.shell: |
      install -o nitor -g nitor -m 600 -D /dev/null /home/nitor/.ssh/authorized_keys
      echo "{{ lookup('ansible.builtin.url', 'http://{{ provision_src }}/personal.pubkey') }}" >> /home/nitor/.ssh/authorized_keys
      
  - name: Configure ansible user
    ansible.builtin.user:
      name: ansible
      comment: "Ansible automation user"
      uid: 1201
      groups: sudo,adm

  - name: Add ansible authorized key
    ansible.builtin.shell: |
      install -o ansible -g ansible -m 600 -D /dev/null /home/ansible/.ssh/authorized_keys
      echo "{{ lookup('ansible.builtin.url', 'http://{{ provision_src }}/ansible.pubkey') }}" >> /home/ansible/.ssh/authorized_keys

  - name: Report to chat channel
    ansible.builtin.shell: |
      webhook=$(curl http://{{ provision_src }}/webhook.url)
      echo {\"text\":\"New system provisioned --- $(hostname) $(hostname -I)\"} | curl -X POST --data @- $webhook
